name: Run Apex Tests (Cron)

on:
  schedule:
    # 16:30 WIB = 09:30 UTC
    - cron: "50 9 * * *"
    - cron: "55 16 * * *"
  workflow_dispatch: # untuk manual run

jobs:
  run-apex-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout (opsional tapi best practice)
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Install Salesforce CLI
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli


      # 3. Authenticate Salesforce (JWT)
      - name: Authenticate Salesforce
        run: |
          sf org login jwt \
            --client-id 3MVG9Za5EbktTiWZ.Mfg7ql0EEo61IpUKC0D7Jq0vQh02pIKcKHh7K.KEcT6AZkCA.o.F9w8tMp5Q551N1vqH \
            --jwt-key-file server-production.key \
            --username rizki.nuriman@bfisupport.prod.sit2 \
            --instance-url https://test.salesforce.com \
            --alias sit

      # 4. Run Apex Test (RunLocalTest)
      - name: Get Apex Test Result
        run: |
          sf apex run test \
          --test-level RunLocalTests \
          --code-coverage \
          --target-org sit \
          --wait 60


            
